insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");
insert into projects (title,category,funding_goal, start_date, end_date) values ("name","cat",1000,"june 2020","jan 2021");

insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);
insert into users (name,age) values ("Nick",33);


insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);
insert into pledges (amount,user_id,project_id) values (250,1,6);